#!/usr/bin/env python3
"""Process the team-generated icon sheets into individual game-ready PNGs.

Input : two magenta-background grids generated by ChatGPT (GPT Image).
Output: src/assets/icons/<assetKey>.png — magenta keyed out (with edge despill),
        trimmed, and centered on a uniform 64x64 transparent square so every icon
        shares one size/aspect and the UI can scale them uniformly.

Run: python3 tools/process_icons.py /path/to/sheet1.png /path/to/sheet2.png
"""
import os
import sys
from PIL import Image

OUT = os.path.join(os.path.dirname(__file__), "..", "src", "assets", "icons")
os.makedirs(OUT, exist_ok=True)

CANVAS = 64       # final square size
MARGIN = 4        # transparent padding inside the canvas
LO, HI = 95, 175  # magenta "g-deficit" ramp: <=LO opaque, >=HI transparent

# Cell -> asset key value, in the row-major order the sheets were generated.
SHEET1 = (4, 3, [
    "icon_turnip", "icon_carrot", "icon_radish", "icon_turnip_seed",
    "icon_carrot_seed", "icon_radish_seed", "icon_egg", "icon_berry",
    "icon_sword", "icon_armor", "icon_ruin_shard", "icon_shadow_wisp",
])
SHEET2 = (5, 1, [
    "icon_starless_helm", "icon_starless_plate", "icon_starless_gauntlets",
    "icon_starless_greaves", "icon_starless_blade",
])


def key_magenta(cell):
    """Return RGBA cell with the flat magenta background turned transparent.

    Uses g-deficit = mean(R,B) - G, which is huge for pure magenta (#FF00FF) but
    small for real content — including the purple/indigo icons, whose green
    channel is well above zero. Edge (partial-alpha) pixels get a light despill
    so no pink halo survives against the dark outlines.
    """
    cell = cell.convert("RGB")
    px = cell.load()
    w, h = cell.size
    out = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    op = out.load()
    for y in range(h):
        for x in range(w):
            r, g, b = px[x, y]
            gd = (r + b) / 2 - g
            if gd <= LO:
                a = 255
            elif gd >= HI:
                a = 0
            else:
                a = round(255 * (HI - gd) / (HI - LO))
            if 0 < a < 255:  # edge: despill toward the green channel
                r = min(r, g + 30)
                b = min(b, g + 30)
            op[x, y] = (r, g, b, a)
    return out


def normalize(icon):
    """Trim to content, then center on a CANVAS x CANVAS transparent square."""
    bbox = icon.getbbox()
    if bbox:
        icon = icon.crop(bbox)
    inner = CANVAS - 2 * MARGIN
    scale = min(inner / icon.width, inner / icon.height)
    icon = icon.resize((max(1, round(icon.width * scale)),
                        max(1, round(icon.height * scale))), Image.LANCZOS)
    sq = Image.new("RGBA", (CANVAS, CANVAS), (0, 0, 0, 0))
    sq.alpha_composite(icon, ((CANVAS - icon.width) // 2, (CANVAS - icon.height) // 2))
    return sq


def process(path, cols, rows, keys):
    sheet = Image.open(path).convert("RGB")
    W, H = sheet.size
    n = 0
    for i, key in enumerate(keys):
        c, r = i % cols, i // cols
        box = (round(c * W / cols), round(r * H / rows),
               round((c + 1) * W / cols), round((r + 1) * H / rows))
        icon = normalize(key_magenta(sheet.crop(box)))
        icon.save(os.path.join(OUT, key + ".png"))
        n += 1
    return n


def contact_sheet(keys):
    cols = 6
    rows = (len(keys) + cols - 1) // cols
    sheet = Image.new("RGBA", (cols * CANVAS, rows * CANVAS), (40, 30, 60, 255))
    for i, key in enumerate(keys):
        img = Image.open(os.path.join(OUT, key + ".png"))
        sheet.alpha_composite(img, ((i % cols) * CANVAS, (i // cols) * CANVAS))
    out = os.path.join(os.path.dirname(__file__), "out")
    os.makedirs(out, exist_ok=True)
    sheet.resize((sheet.width * 2, sheet.height * 2), Image.NEAREST).save(
        os.path.join(out, "icons_contact.png"))


def main():
    s1, s2 = sys.argv[1], sys.argv[2]
    process(s1, *SHEET1)
    process(s2, *SHEET2)
    all_keys = SHEET1[2] + SHEET2[2]
    contact_sheet(all_keys)
    print("wrote", len(all_keys), "icons to", os.path.relpath(OUT))


if __name__ == "__main__":
    main()
