// Re-exports the Phaser-free sprite data + helpers so the offline preview renderer
// (tools/preview.mjs) can bundle and render exactly what the game ships. Add a sprite
// here to include it in the review sheets. Not part of the app or the tsconfig build.
export { resolvePixels } from '../src/game/assets/sprites/spriteGrid';
export { palette } from '../src/game/data/palette';
import {
  FARMER_DOWN,
  FARMER_DOWN_WALK_A,
  FARMER_DOWN_WALK_B,
  FARMER_UP,
  FARMER_UP_WALK_A,
  FARMER_UP_WALK_B,
  FARMER_SIDE,
  FARMER_SIDE_WALK_A,
  FARMER_SIDE_WALK_B,
} from '../src/game/assets/sprites/farmer';
import { JAY, SEED_SELLER, BLACKSMITH, VILLAGER } from '../src/game/assets/sprites/characters';
import { CHICKEN } from '../src/game/assets/sprites/chicken';
import {
  CROP_MOUND,
  CROP_SPROUT,
  CROP_LEAFY,
  TURNIP,
  CARROT,
  PUMPKIN,
} from '../src/game/assets/sprites/crops';
import { BUSH_FULL, BUSH_EMPTY } from '../src/game/assets/sprites/bushes';
import { RUIN_MITE, SHADE_PUP, CROP_NIBBLER, RUIN_HEART } from '../src/game/assets/sprites/enemies';
import {
  SHIPPING_BOX,
  DOOR,
  CHEST,
  SIGNPOST,
  ANVIL,
  RUBBLE,
  SEALED_DOOR,
  CACHE_CLOSED,
  CACHE_OPEN,
  COTTAGE,
  STALL,
} from '../src/game/assets/sprites/props';
import {
  ICON_TURNIP,
  ICON_CARROT,
  ICON_PUMPKIN,
  ICON_TURNIP_SEED,
  ICON_CARROT_SEED,
  ICON_PUMPKIN_SEED,
  ICON_EGG,
  ICON_BERRY,
  ICON_SWORD,
  ICON_ARMOR,
  ICON_RUIN_SHARD,
  ICON_SHADOW_WISP,
  ICON_STARLESS_HELM,
  ICON_STARLESS_PLATE,
  ICON_STARLESS_GAUNTLETS,
  ICON_STARLESS_GREAVES,
  ICON_STARLESS_BLADE,
  HEART_FULL,
  HEART_EMPTY,
  SLASH,
} from '../src/game/assets/sprites/icons';

export const SPRITES = {
  farmerDown: FARMER_DOWN,
  farmerDownWalkA: FARMER_DOWN_WALK_A,
  farmerDownWalkB: FARMER_DOWN_WALK_B,
  farmerUp: FARMER_UP,
  farmerUpWalkA: FARMER_UP_WALK_A,
  farmerUpWalkB: FARMER_UP_WALK_B,
  farmerSide: FARMER_SIDE,
  farmerSideWalkA: FARMER_SIDE_WALK_A,
  farmerSideWalkB: FARMER_SIDE_WALK_B,
  jay: JAY,
  seedSeller: SEED_SELLER,
  blacksmith: BLACKSMITH,
  villager: VILLAGER,
  chicken: CHICKEN,
  cropMound: CROP_MOUND,
  cropSprout: CROP_SPROUT,
  cropLeafy: CROP_LEAFY,
  turnip: TURNIP,
  carrot: CARROT,
  pumpkin: PUMPKIN,
  bushFull: BUSH_FULL,
  bushEmpty: BUSH_EMPTY,
  ruinMite: RUIN_MITE,
  shadePup: SHADE_PUP,
  cropNibbler: CROP_NIBBLER,
  ruinHeart: RUIN_HEART,
  shippingBox: SHIPPING_BOX,
  door: DOOR,
  chest: CHEST,
  signpost: SIGNPOST,
  anvil: ANVIL,
  rubble: RUBBLE,
  sealedDoor: SEALED_DOOR,
  cacheClosed: CACHE_CLOSED,
  cacheOpen: CACHE_OPEN,
  cottage: COTTAGE,
  stall: STALL,
  iconTurnip: ICON_TURNIP,
  iconCarrot: ICON_CARROT,
  iconPumpkin: ICON_PUMPKIN,
  iconTurnipSeed: ICON_TURNIP_SEED,
  iconCarrotSeed: ICON_CARROT_SEED,
  iconPumpkinSeed: ICON_PUMPKIN_SEED,
  iconEgg: ICON_EGG,
  iconBerry: ICON_BERRY,
  iconSword: ICON_SWORD,
  iconArmor: ICON_ARMOR,
  iconRuinShard: ICON_RUIN_SHARD,
  iconShadowWisp: ICON_SHADOW_WISP,
  iconHelm: ICON_STARLESS_HELM,
  iconPlate: ICON_STARLESS_PLATE,
  iconGauntlets: ICON_STARLESS_GAUNTLETS,
  iconGreaves: ICON_STARLESS_GREAVES,
  iconBlade: ICON_STARLESS_BLADE,
  heartFull: HEART_FULL,
  heartEmpty: HEART_EMPTY,
  slash: SLASH,
};
